"""Build a Lua database of puzzle entries with salted SHA-256 answer hashes.

Why this exists
    The "phrase that pays" / 23 C0iNS puzzle pattern needs the answer text
    out of the .pdx so anyone who runs `pdc -d` can't grep the binary for
    the solutions. The factory build step ships only the SALTED HASH of
    each answer. The Playdate engine hashes player input the same way and
    compares.

Important correction vs the original proposal
    The first draft hashed `SALT + COIN_<i>` — a CONSTANT per coin index.
    That hash never depends on player input, so it can't gate anything.
    This corrected version hashes `SALT + normalised(answer_phrase)` per
    coin, so player input drives the match.

Salt caveat (be honest with yourself)
    Any SALT shipped inside a .pdx is extractable with `pdc -d`. 16-char
    SHA-256 = 64 bits of entropy. Combined with an extractable salt and
    a small phrase length, this is brute-forceable offline. Real
    anti-cheat needs either:
      - per-device entropy (Playdate has no secure enclave; not feasible)
      - server-side validation (no online in HAKCD)
      - or a per-coin one-time-pad keyed off something the player already
        knows / has discovered in-game (e.g. derive salt from coin N-1's
        answer, so leaking the salt requires already solving the prior
        puzzle).
    This builder writes the truncated-SHA pattern. Treat it as anti-grep
    not anti-determined-attacker.

Usage
    python -m tools.build_lua_db \
        --project hakcd \
        --project-local-path /home/hakcer/projects/personal/hakcd \
        --phrases-file phrases.yaml \
        [--salt-env APP_SECRET_SALT] \
        [--out source/data/coins_db.lua] \
        [--truncate 16]

phrases.yaml format (example)
    salt: DEADLINE_BBS_1998     # optional, env --salt-env wins if set
    coins:
      - id: 0
        title: WELCOME COIN
        state: minted
        phrase: WELCOME
      - id: 1
        title: ROTARY DIAL
        state: available
        phrase: pulse dial 7 1 4 long short long
      - id: 2
        title: LOST WAGES
        state: available
        phrase: # blank or omitted -> validation_hash null + state forced to locked

Output (Lua)
    -- AUTO-GENERATED by visual_pack_factory.build_lua_db. Do not edit.
    local coins_db = {
      ["0"] = {
        id = 0, title = "WELCOME COIN", state = "minted",
        phrase_known = true, puzzle_complete = true,
        validation_hash = "<16-hex>",
        hints_seen = {},
      },
      ...
    }
    return coins_db
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
import unicodedata
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pack_config import (  # noqa: E402
    assert_slug,
    dump_yaml,
    load_yaml,
)
from tools._common import emit, fail, run  # noqa: E402


DEFAULT_TRUNCATE = 16
DEFAULT_OUT = "source/data/coins_db.lua"
ALLOWED_STATES = {"minted", "available", "locked", "hidden"}


def normalise_phrase(s: str) -> str:
    """Normalise so trivial player variants still match.

    - NFKD unicode normalisation
    - strip accents
    - lowercase
    - collapse internal whitespace to single space
    - strip leading/trailing whitespace
    - drop trailing punctuation runs
    Player input must be normalised the same way in-engine before hash.
    """
    if s is None:
        return ""
    nfkd = unicodedata.normalize("NFKD", str(s))
    no_accent = "".join(c for c in nfkd if not unicodedata.combining(c))
    lowered = no_accent.lower()
    collapsed = re.sub(r"\s+", " ", lowered).strip()
    stripped = re.sub(r"[.,!?;:]+$", "", collapsed)
    return stripped


def phrase_hash(salt: str, phrase: str, truncate: int = DEFAULT_TRUNCATE) -> str:
    if not phrase:
        return ""
    payload = f"{salt}|{phrase}".encode("utf-8")
    return hashlib.sha256(payload).hexdigest()[:truncate]


def lua_str(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_bool(b: bool) -> str:
    return "true" if b else "false"


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Compile a salted-hash Lua puzzle DB.")
    p.add_argument("--project", required=True, help="project id (slug)")
    p.add_argument("--project-local-path", required=True,
                   help="absolute path to the consuming game repo")
    p.add_argument("--phrases-file", required=True,
                   help="YAML file with the coin/puzzle config")
    p.add_argument("--salt-env", default="APP_SECRET_SALT",
                   help="env var holding the build-time salt (default "
                        "APP_SECRET_SALT). Falls back to phrases.yaml 'salt' "
                        "field then 'DEFAULT_SALT_OVERRIDE_ME'.")
    p.add_argument("--out", default=DEFAULT_OUT,
                   help="relative output path inside project repo")
    p.add_argument("--truncate", type=int, default=DEFAULT_TRUNCATE,
                   help="truncate SHA-256 hex to N chars (default 16)")
    p.add_argument("--db-name", default="coins_db",
                   help="local var + module name in emitted Lua")
    return p


def main(args: argparse.Namespace) -> None:
    assert_slug(args.project, "project")
    repo = Path(args.project_local_path).resolve()
    if not repo.is_dir():
        fail("repo_not_found", {"path": str(repo)})

    cfg = load_yaml(Path(args.phrases_file).resolve())
    if not isinstance(cfg, dict):
        fail("phrases_file_invalid", {"path": args.phrases_file})
    salt = os.environ.get(args.salt_env) or cfg.get("salt") or \
        "DEFAULT_SALT_OVERRIDE_ME"
    coins = cfg.get("coins") or []
    if not isinstance(coins, list) or not coins:
        fail("no_coins_defined", {})

    rows: list[dict] = []
    for c in coins:
        if not isinstance(c, dict):
            continue
        coin_id = c.get("id")
        title = str(c.get("title") or "???")
        state = c.get("state") or "locked"
        if state not in ALLOWED_STATES:
            state = "locked"
        raw_phrase = c.get("phrase") or ""
        norm = normalise_phrase(raw_phrase)
        if not norm:
            # No phrase known yet — force locked + null hash so engine
            # treats this coin as gated by something other than text input.
            state = "locked" if state == "available" else state
            v_hash = ""
        else:
            v_hash = phrase_hash(salt, norm, args.truncate)
        rows.append({
            "id": coin_id,
            "title": title,
            "state": state,
            "phrase_known": bool(norm),
            "puzzle_complete": state == "minted",
            "validation_hash": v_hash,
            "norm_len": len(norm),
        })

    db_name = args.db_name
    lines: list[str] = [
        "-- AUTO-GENERATED by services/visual_pack_factory/tools/build_lua_db.py",
        "-- Salted-SHA256 puzzle DB. Do NOT edit by hand.",
        f"-- truncate={args.truncate} salt_env={args.salt_env}",
        "",
        f"local {db_name} = {{",
    ]
    for r in rows:
        key = lua_str(str(r["id"]))
        lines.append(f"  [{key}] = {{")
        lines.append(f"    id = {int(r['id'])},")
        lines.append(f"    title = {lua_str(r['title'])},")
        lines.append(f"    state = {lua_str(r['state'])},")
        lines.append(f"    phrase_known = {lua_bool(r['phrase_known'])},")
        lines.append(f"    puzzle_complete = {lua_bool(r['puzzle_complete'])},")
        lines.append(f"    validation_hash = {lua_str(r['validation_hash'])},")
        lines.append("    hints_seen = {},")
        lines.append("  },")
    lines.append("}")
    lines.append("")
    lines.append("-- Engine-side companion: hash player input the same way:")
    lines.append("--   local sha = playdate.simulator and require('sha2') or nil  -- shim")
    lines.append("--   local function check(coin_id, player_text)")
    lines.append("--     local row = " + db_name + "[tostring(coin_id)]")
    lines.append("--     if not row or row.validation_hash == '' then return false end")
    lines.append(f"--     local h = sha256(SALT..'|'..normalise(player_text)):sub(1, {args.truncate})")
    lines.append("--     return h == row.validation_hash")
    lines.append("--   end")
    lines.append("")
    lines.append(f"return {db_name}")

    out_path = repo / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    emit({
        "out": str(out_path),
        "coin_count": len(rows),
        "with_hash": sum(1 for r in rows if r["validation_hash"]),
        "no_phrase": sum(1 for r in rows if not r["validation_hash"]),
        "salt_source": ("env:" + args.salt_env) if os.environ.get(args.salt_env)
                       else "phrases_file" if cfg.get("salt") else "default_fallback",
        "truncate": args.truncate,
    })


if __name__ == "__main__":
    run(main)
