-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_update(event)
  pulp.event = event or pulp.event or {}
  pulp.vars.a = (pulp.vars.b + pulp.vars.c)
  pulp.vars.d = (pulp.vars.b - pulp.vars.c)
  pulp.vars.e = (pulp.vars.b * pulp.vars.c)
  pulp.vars.f = (pulp.vars.b / pulp.vars.c)
end
pulp.listen('game', 'update', game_on_update)

