-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_load(event)
  pulp.event = event or pulp.event or {}
  pulp.bpm(140)
end
pulp.listen('game', 'load', game_on_load)

