-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_update(event)
  pulp.event = event or pulp.event or {}
  if (pulp.vars.a == pulp.vars.b) then
    pulp.log("eq")
  end
  if (pulp.vars.a ~= pulp.vars.b) then
    pulp.log("ne")
  end
  if (pulp.vars.a < pulp.vars.b) then
    pulp.log("lt")
  end
  if (pulp.vars.a > pulp.vars.b) then
    pulp.log("gt")
  end
  if (pulp.vars.a <= pulp.vars.b) then
    pulp.log("le")
  end
  if (pulp.vars.a >= pulp.vars.b) then
    pulp.log("ge")
  end
end
pulp.listen('game', 'update', game_on_update)

