-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_update(event)
  pulp.event = event or pulp.event or {}
  pulp.vars.x = (pulp.vars.x or 0) + 2
  pulp.vars.y = (pulp.vars.y or 0) - 1
  pulp.vars.z = (pulp.vars.z or 0) * 3
  pulp.vars.w = (pulp.vars.w or 0) / 2
end
pulp.listen('game', 'update', game_on_update)

