-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_draw(event)
  pulp.event = event or pulp.event or {}
  pulp.window(0, 0, 200, 80)
  pulp.label("x", 0, 0)
  pulp.fill(0, 0, 5, 5, 1)
end
pulp.listen('game', 'draw', game_on_draw)

