-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_draw(event)
  pulp.event = event or pulp.event or {}
  pulp.say(pulp.fmt("lives: {3,0:lives}", {lives = pulp.vars.lives}))
end
pulp.listen('game', 'draw', game_on_draw)

