-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_confirm(event)
  pulp.event = event or pulp.event or {}
  pulp.menu({
    text = "choose",
    options = {
      { label = "start", run = function()
        pulp.say("begin")
      end },
      { label = "quit", run = function()
        pulp.fin("bye")
      end },
    },
  })
end
pulp.listen('game', 'confirm', game_on_confirm)

