-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_update(event)
  pulp.event = event or pulp.event or {}
  while (pulp.vars.a < 5) do
    while (pulp.vars.b < 3) do
      pulp.vars.b = (pulp.vars.b or 0) + 1
    end
    pulp.vars.a = (pulp.vars.a or 0) + 1
  end
end
pulp.listen('game', 'update', game_on_update)

