-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_update(event)
  pulp.event = event or pulp.event or {}
  if (pulp.vars.a == 1) then
    if (pulp.vars.b == 2) then
      pulp.say("inner")
    end
  end
end
pulp.listen('game', 'update', game_on_update)

