-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_enter(event)
  pulp.event = event or pulp.event or {}
  pulp.log("entered")
end
pulp.listen('game', 'enter', game_on_enter)

