-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_loop(event)
  pulp.event = event or pulp.event or {}
  pulp.log("tick")
end
pulp.listen('game', 'loop', game_on_loop)

