-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_confirm(event)
  pulp.event = event or pulp.event or {}
  pulp.event.last = pulp.query.solid(3, 4)
  pulp.event.last = pulp.query.id(3, 4)
end
pulp.listen('game', 'confirm', game_on_confirm)

