-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_load(event)
  pulp.event = event or pulp.event or {}
  pulp.vars.a = 5
  pulp.vars.b = pulp.vars.a
end
pulp.listen('game', 'load', game_on_load)

