-- Generated by pulp_transpiler. Do not edit by hand.
-- scope=game namespace=game
local pulp = pulp or _G.pulp
if not pulp then error("pulp runtime not loaded") end

function game_on_confirm(event)
  pulp.event = event or pulp.event or {}
  pulp.wait(1)
  pulp.then_after(function()
    pulp.say("after")
  end)
end
pulp.listen('game', 'confirm', game_on_confirm)

