'use strict';

// AST -> Lua codegen.
// Produces text targeting the runtime in pulp_runtime_lua/pulp_runtime.lua.

const ROOT_OBJECTS = new Set(['event', 'config', 'datetime']);

// PulpScript keyword event names that are valid handler triggers.
const KNOWN_EVENTS = new Set([
  'load', 'start', 'enter', 'exit', 'finish', 'loop', 'update', 'bump',
  'confirm', 'cancel', 'crank', 'dock', 'undock', 'draw', 'interact',
  'collect', 'change', 'select', 'dismiss', 'invalid', 'any',
]);

// PulpScript-style query commands that have a return value. These are exposed
// in the runtime as `pulp.query.<name>(...)` and we emit them as expression-
// position calls when they appear inside expressions. As bare statements they
// are still legal (the runtime stores the result in `pulp.event.last`).
const QUERY_COMMANDS = new Set([
  'random', 'floor', 'ceil', 'round',
  'sine', 'cosine', 'tangent', 'radians', 'degrees',
  'solid', 'type', 'id', 'name', 'invert', 'frame',
]);

function generate(ast, opts) {
  const options = opts || {};
  const namespace = options.namespace || 'game';
  const scope = options.scope || 'game';
  const warnings = [];

  const lines = [];
  lines.push('-- Generated by pulp_transpiler. Do not edit by hand.');
  lines.push(`-- scope=${scope} namespace=${namespace}`);
  lines.push('local pulp = pulp or _G.pulp');
  lines.push('if not pulp then error("pulp runtime not loaded") end');
  lines.push('');

  if (ast && ast.type === 'Program') {
    for (const stmt of ast.body) emitTopLevel(stmt, lines, namespace, warnings);
  }

  return { lua: lines.join('\n') + '\n', warnings };
}

function emitTopLevel(stmt, lines, namespace, warnings) {
  if (stmt.type === 'EventHandler') {
    if (!KNOWN_EVENTS.has(stmt.event) && stmt.event !== '<unknown>') {
      warnings.push({ line: stmt.line, col: stmt.col,
        message: `unknown event '${stmt.event}' — treating as custom handler` });
    }
    const fnName = `${namespace}_on_${stmt.event}`;
    lines.push(`function ${fnName}(event)`);
    lines.push('  pulp.event = event or pulp.event or {}');
    const inner = emitBlock(stmt.body, 1);
    if (inner) lines.push(inner);
    lines.push('end');
    lines.push(`pulp.listen('${namespace}', '${stmt.event}', ${fnName})`);
    lines.push('');
    return;
  }
  // Bare top-level statements are wrapped into a `__main` block so they run
  // at module load.
  warnings.push({ line: stmt.line || 1, col: stmt.col || 1,
    message: 'top-level statement outside an event handler — wrapped in __main' });
  const inner = emitBlock([stmt], 1);
  lines.push('do');
  if (inner) lines.push(inner);
  lines.push('end');
}

function pad(level) { return '  '.repeat(level); }

function emitBlock(stmts, level) {
  const out = [];
  for (const s of stmts) {
    const line = emitStatement(s, level);
    if (line != null && line !== '') out.push(line);
  }
  return out.join('\n');
}

function emitStatement(s, level) {
  const ind = pad(level);
  switch (s.type) {
    case 'Assignment': return ind + emitAssignment(s);
    case 'IncDec':     return ind + emitIncDec(s);
    case 'If':         return emitIf(s, level);
    case 'While':      return emitWhile(s, level);
    case 'Tell':       return emitTell(s, level);
    case 'Done':       return ind + 'do return end';
    case 'Call':       return emitCall(s, level);
    default:
      return ind + `-- TODO: ${s.type}`;
  }
}

function emitAssignment(s) {
  const lhs = emitLValue(s.target);
  const rhs = emitExpr(s.value);
  if (s.op === '=') return `${lhs} = ${rhs}`;
  // Compound assignment.
  const opChar = s.op[0]; // + - * /
  return `${lhs} = (${lhs} or 0) ${opChar} ${rhs}`;
}

function emitIncDec(s) {
  const lhs = emitLValue(s.target);
  if (s.op === '++') return `${lhs} = (${lhs} or 0) + 1`;
  return `${lhs} = (${lhs} or 0) - 1`;
}

function emitIf(s, level) {
  const ind = pad(level);
  const out = [];
  out.push(`${ind}if ${emitExpr(s.cond)} then`);
  const th = emitBlock(s.then, level + 1);
  if (th) out.push(th);
  for (const e of s.elifs) {
    out.push(`${ind}elseif ${emitExpr(e.cond)} then`);
    const b = emitBlock(e.body, level + 1);
    if (b) out.push(b);
  }
  if (s.else) {
    out.push(`${ind}else`);
    const el = emitBlock(s.else, level + 1);
    if (el) out.push(el);
  }
  out.push(`${ind}end`);
  return out.join('\n');
}

function emitWhile(s, level) {
  const ind = pad(level);
  const out = [];
  out.push(`${ind}while ${emitExpr(s.cond)} do`);
  const b = emitBlock(s.body, level + 1);
  if (b) out.push(b);
  out.push(`${ind}end`);
  return out.join('\n');
}

function emitTell(s, level) {
  const ind = pad(level);
  const out = [];
  const targetExpr = s.target.type === 'TupleExpression'
    ? '{' + s.target.elements.map(emitExpr).join(', ') + '}'
    : emitExpr(s.target);
  out.push(`${ind}pulp.tell(${targetExpr}, function()`);
  const b = emitBlock(s.body, level + 1);
  if (b) out.push(b);
  out.push(`${ind}end)`);
  return out.join('\n');
}

function emitCall(s, level) {
  const ind = pad(level);
  const name = s.name;

  // Strip positional markers (`at`, `in`, `to`) — they are sugar in source,
  // we recover semantics from the count + order of remaining args.
  const args = s.args.filter(a => a.type !== 'Marker');

  // Special-cased commands that map to a more ergonomic Lua surface:
  if (name === 'call' || name === 'emit' || name === 'mimic') {
    const ev = args[0] ? emitExpr(args[0]) : '""';
    return `${ind}pulp.${name}(${ev})`;
  }

  if (name === 'goto') {
    // goto x,y [in "room"]
    const parts = args.map(emitExpr);
    // `goto` is a reserved keyword in Lua 5.2+ so we must use bracket access.
    return `${ind}pulp["goto"](${parts.join(', ')})`;
  }

  if (name === 'tell') {
    // Shouldn't appear (Tell node), but tolerate.
    return `${ind}-- (tell as call form)`;
  }

  if (name === 'ask' || name === 'menu') {
    // Build options table.
    const optLines = [];
    optLines.push(`${ind}pulp.${name}({`);
    optLines.push(`${ind}  text = ${args[0] ? emitExpr(args[0]) : '""'},`);
    if (s.options && s.options.length) {
      optLines.push(`${ind}  options = {`);
      for (const op of s.options) {
        optLines.push(`${ind}    { label = ${quote(op.label)}, run = function()`);
        const b = emitBlock(op.body, level + 3);
        if (b) optLines.push(b);
        optLines.push(`${ind}    end },`);
      }
      optLines.push(`${ind}  },`);
    }
    optLines.push(`${ind}})`);
    return optLines.join('\n');
  }

  if (name === 'say') {
    const text = args[0] ? emitExpr(args[0]) : '""';
    const rest = args.slice(1).map(emitExpr);
    const opt = rest.length
      ? `, { at = { ${rest.join(', ')} } }`
      : '';
    let out = `${ind}pulp.say(${text}${opt})`;
    if (s.block) {
      out += '\n' + `${ind}pulp.then_after(function()`;
      const b = emitBlock(s.block, level + 1);
      if (b) out += '\n' + b;
      out += '\n' + `${ind}end)`;
    }
    return out;
  }

  if (name === 'fin') {
    const text = args[0] ? emitExpr(args[0]) : '""';
    return `${ind}pulp.fin(${text})`;
  }

  if (name === 'swap')   return `${ind}pulp.swap(${args.map(emitExpr).join(', ')})`;
  if (name === 'frame')  return `${ind}pulp.frame(${args.map(emitExpr).join(', ')})`;
  if (name === 'play') {
    const out = [`${ind}pulp.play(${args.map(emitExpr).join(', ')})`];
    if (s.block) {
      out.push(`${ind}pulp.then_after(function()`);
      const b = emitBlock(s.block, level + 1);
      if (b) out.push(b);
      out.push(`${ind}end)`);
    }
    return out.join('\n');
  }

  if (name === 'hide')   return `${ind}pulp.hide()`;
  if (name === 'window') return `${ind}pulp.window(${args.map(emitExpr).join(', ')})`;
  if (name === 'label')  return `${ind}pulp.label(${args.map(emitExpr).join(', ')})`;
  if (name === 'fill')   return `${ind}pulp.fill(${args.map(emitExpr).join(', ')})`;
  if (name === 'crop')   return `${ind}pulp.crop(${args.map(emitExpr).join(', ')})`;
  if (name === 'draw')   return `${ind}pulp.draw(${args.map(emitExpr).join(', ')})`;

  if (name === 'listen') return `${ind}pulp.listen_input()`;
  if (name === 'ignore') return `${ind}pulp.ignore_input()`;
  if (name === 'act')    return `${ind}pulp.act()`;

  if (name === 'sound')  return `${ind}pulp.sound(${args.map(emitExpr).join(', ')})`;
  if (name === 'once') {
    const out = [`${ind}pulp.once(${args.map(emitExpr).join(', ')})`];
    if (s.block) {
      out.push(`${ind}pulp.then_after(function()`);
      const b = emitBlock(s.block, level + 1);
      if (b) out.push(b);
      out.push(`${ind}end)`);
    }
    return out.join('\n');
  }
  if (name === 'loop')   return `${ind}pulp.loop(${args.map(emitExpr).join(', ')})`;
  if (name === 'stop')   return `${ind}pulp.stop(${args.map(emitExpr).join(', ')})`;
  if (name === 'bpm')    return `${ind}pulp.bpm(${args.map(emitExpr).join(', ')})`;

  if (name === 'store')  return `${ind}pulp.store(${args.map(emitExpr).join(', ')})`;
  if (name === 'restore')return `${ind}pulp.restore(${args.map(emitExpr).join(', ')})`;
  if (name === 'toss')   return `${ind}pulp.toss(${args.map(emitExpr).join(', ')})`;

  if (name === 'log')    return `${ind}pulp.log(${args.map(emitExpr).join(', ')})`;
  if (name === 'dump')   return `${ind}pulp.dump()`;

  if (name === 'wait') {
    const out = [`${ind}pulp.wait(${args.map(emitExpr).join(', ')})`];
    if (s.block) {
      out.push(`${ind}pulp.then_after(function()`);
      const b = emitBlock(s.block, level + 1);
      if (b) out.push(b);
      out.push(`${ind}end)`);
    }
    return out.join('\n');
  }
  if (name === 'shake') {
    const out = [`${ind}pulp.shake(${args.map(emitExpr).join(', ')})`];
    if (s.block) {
      out.push(`${ind}pulp.then_after(function()`);
      const b = emitBlock(s.block, level + 1);
      if (b) out.push(b);
      out.push(`${ind}end)`);
    }
    return out.join('\n');
  }

  // Query commands at statement position stash their result in pulp.event.last
  if (QUERY_COMMANDS.has(name)) {
    return `${ind}pulp.event.last = pulp.query.${name}(${args.map(emitExpr).join(', ')})`;
  }

  // Unknown command — emit a runtime call but warn.
  return `${ind}pulp.call_command(${quote(name)}, {${args.map(emitExpr).join(', ')}})`;
}

function emitLValue(node) {
  if (node.type === 'Identifier') {
    if (ROOT_OBJECTS.has(node.name)) return `pulp.${node.name}`;
    return `pulp.vars.${node.name}`;
  }
  if (node.type === 'Member') {
    return `${emitLValue(node.object)}.${node.property}`;
  }
  return '<<bad lvalue>>';
}

function emitExpr(node) {
  switch (node.type) {
    case 'NumberLiteral': return formatNumber(node.value);
    case 'BoolLiteral':   return node.value ? 'true' : 'false';
    case 'StringLiteral': return formatString(node.value);
    case 'Identifier':    return emitLValue(node);
    case 'Member':        return emitLValue(node);
    case 'Unary':
      return `(-${emitExpr(node.operand)})`;
    case 'Binary':
      return `(${emitExpr(node.left)} ${luaOp(node.op)} ${emitExpr(node.right)})`;
    case 'TupleExpression':
      return '{' + node.elements.map(emitExpr).join(', ') + '}';
    default:
      return 'nil';
  }
}

function formatNumber(n) {
  if (Number.isInteger(n)) return String(n);
  return String(n);
}

function luaOp(op) {
  if (op === '!=') return '~=';
  return op;
}

// Emit a Lua string literal. If the source string contains `{var}` or
// `{n,c:var}` placeholders, wrap it in pulp.fmt(...).
function formatString(str) {
  const placeholders = extractPlaceholders(str);
  if (placeholders.length === 0) return quote(str);
  // Build the vars table.
  const seen = new Set();
  const entries = [];
  for (const p of placeholders) {
    if (seen.has(p.name)) continue;
    seen.add(p.name);
    entries.push(`${luaKey(p.name)} = pulp.vars.${p.name}`);
  }
  return `pulp.fmt(${quote(str)}, {${entries.join(', ')}})`;
}

function extractPlaceholders(str) {
  const out = [];
  let i = 0;
  while (i < str.length) {
    const c = str[i];
    if (c === '{') {
      const end = str.indexOf('}', i);
      if (end < 0) break;
      const inside = str.slice(i + 1, end);
      // forms: "name", "n,c:name", "name:n,c", "embed:tile"
      let name = inside;
      if (inside.includes(':')) {
        const parts = inside.split(':');
        if (parts[0] === 'embed') { i = end + 1; continue; } // tile embed — runtime handles
        // The variable name is whichever side ISN'T the format spec.
        // Format spec contains a comma; var name doesn't.
        if (parts[0].includes(',')) name = parts[1];
        else name = parts[0];
      }
      name = name.trim();
      if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) out.push({ name });
      i = end + 1;
    } else {
      i++;
    }
  }
  return out;
}

function luaKey(name) {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
  return `[${quote(name)}]`;
}

function quote(s) {
  // Lua double-quoted string. Escape \ " and control chars.
  let out = '"';
  for (const ch of String(s)) {
    if (ch === '\\') out += '\\\\';
    else if (ch === '"') out += '\\"';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else out += ch;
  }
  out += '"';
  return out;
}

module.exports = { generate, KNOWN_EVENTS };
